### ISSUE TITLE
fixed 614

### ISSUE THREAD

**Issue by ego008** [yueyoum/seven-cow#2]
七牛有个上传防覆盖机制，即同文件名同内容文件上传则更新文件puttime，若同文件名不同内容则返回614 错误代码。

下面修改可强制覆盖

```
        url = '%s/upload' % UP_HOST
-        token = self.generate_upload_token(scope)
+        token = self.generate_upload_token('%s:%s' % (scope, filename))
        names = names or {}
```

文档： http://developer.qiniu.com/docs/v6/api/reference/security/put-policy.html

**Comment by yueyoum** [comment]
Thanks, 欢迎提交一个 pull requests。

**Comment by yueyoum** [comment]
Hi, 已经添加这个特性。
