### ISSUE TITLE
这个不能创建缩略图吧？

### ISSUE THREAD

**Issue by hugleecool** [yueyoum/seven-cow#3]
python菜鸟，为网站添加上传图片功能。需求：缩略图。
另外，这个sdk你还在更新不，如果七牛自己更新了，这边不能用了怎么办呀。。

**Comment by yueyoum** [comment]
最近没有维护，
如果遇到不能用的情况，请报个issue，我会跟进维护的

这个没有缩略图功能，仅仅是上传文件到七牛

我记得七牛有自动获得缩略图的功能，好像是url后面跟 ? size 参数， 你看看文档
